- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Download Frontend from Nexus
  get_url:
    url: http://172.31.11.10:8081/repository/frontendd/frontendd-{{APP_VERSION}}.zip
    dest: /tmp/frontendd.zip
    username: admin
    password: admin123

- name: Delete the default content
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    

- name: Create HtDocs Directory
  file:
    path: /var/www/html/frontendd
    state: directory

- name: Unzip the Downloaded Content
  unarchive:
    src: /tmp/frontendd.zip
    dest: /var/www/html/frontendd
    remote_src: yes

- name: Update Todo Config file
  template:
    src: todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf

- name: Start Nginx
  systemd:
    state: restarted
    name: nginx
    enabled: yes
